### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by wuxiaolan91** [CodeFalling/hexo-asset-image#1]
$ npm install https://github.com/CodeFalling/hexo-asset-image --save
npm ERR! fetch failed https://github.com/CodeFalling/hexo-asset-image
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/CodeFalling/hexo-asset-image
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/CodeFalling/hexo-asset-image
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "https://github.com/CodeFalling/hexo-asset-image" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! fetch failed with status code 406
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     F:\github\wuxiaolan91.github.io\npm-debug.log

**Comment by xcodebuild** [comment]
Try `npm install hexo-asset-image --save` ?
