### ISSUE TITLE
fail to install in linux. 

### ISSUE THREAD

**Issue by ziyuanjun** [CodeFalling/hexo-asset-image#10]
my input and output information: 

> npm install hexo-asset-image --save
> hexo-site@0.0.0 /home/ziyuan/Program/Hexo
> └── hexo-asset-image@0.0.2 
> 
> npm WARN optional Skipping failed optional dependency /hexo/hexo-fs/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
> npm WARN optional Skipping failed optional dependency /hexo/nunjucks/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
> npm WARN optional Skipping failed optional dependency /hexo-deployer-git/hexo-fs/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
> npm WARN optional Skipping failed optional dependency /hexo-math/hexo-fs/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

**Comment by daiyi** [comment]
I got these warnings for `hexo-asset-image@0.0.3` on linux mint using `node v6.9.1`, but it did finish installing:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by xcodebuild** [comment]
This is warning, just ignore it.

`fsevents` is only for macOS
