### ISSUE TITLE
中文编码问题

### ISSUE THREAD

**Issue by binblog** [CodeFalling/hexo-asset-image#12]
您好，我在使用时发现该插件会将中文修改为unicode编码，而在index.js中cheerio.load方法下添加参数：decodeEntities: false，可以避免这个问题
      var $ = cheerio.load(data[key], {
        ignoreWhitespace: false,
        xmlMode: false,
        lowerCaseTags: false,
		decodeEntities: false
      });

参考：https://cnodejs.org/topic/54bdd639514ea9146862ac37， 不知道可不可以修改一下此处。

**Comment by xcodebuild** [comment]
抱歉这么晚才看到，多谢，已经修改。

**Comment by mutoe** [comment]
这个问题在我这里又复现了
```
node 6.2.2
hexo 3.2.2
hexo-asset-image: 0.0.3
os: Windows_NT 10.0.14393 x64
```
前来寻求帮助

**Comment by mutoe** [comment]
官方似乎刚更新了图片的加载方式
https://hexo.io/zh-cn/docs/asset-folders.html
