### ISSUE TITLE
公共图片引用

### ISSUE THREAD

**Issue by zhyihui** [CodeFalling/hexo-asset-image#17]
不知道有没有办法引用公共图片，图片放在source/img下

**Comment by daiyi** [comment]
you should be able to do that automatically: https://hexo.io/docs/asset-folders.html#Global-Asset-Folder (sorry my chinese is really bad hopefully the docs can explain better than me!!)

**Comment by zhyihui** [comment]
@daiyi thanks for your reply!do you mean that I don't need use the 'hexo-asset-image' plugin with my situation?
by the way, I have not a good english level too.

**Comment by xcodebuild** [comment]
对于公共图片直接引用即可，不需要使用 `hexo-asset-image`
