### ISSUE TITLE
permalink: :year/:month/:day/:title 如果加上“.html”会有问题

### ISSUE THREAD

**Issue by kay-refresh** [CodeFalling/hexo-asset-image#19]
刚刚测试，如果在 “_config..yml” 里，把 permalink: :year/:month/:day/:title加上“.html”，该插件就无法正常使用，生成时路径会把 “.html” 也一起生成，最后生成路径会为“D:\hexo\template\public\2017\03\14\jqexamplee.html\logo.jpg”。除了把“.html”去掉，不知道有没有其他方法可以修改？

**Comment by xcodebuild** [comment]
Same with https://github.com/xcodebuild/hexo-asset-image/issues/21
