### ISSUE TITLE
Failed to Show Image

### ISSUE THREAD

**Issue by seasonxuan** [CodeFalling/hexo-asset-image#2]
file _config.yml
`post_asset_folder: true`
file sample.md
`![image1](sample/image1.jpg)`
image sample/image1.jpg

but generate file index.html
 `<img src="/2016/01/31/sample/sample/image1.jpg" alt="image1">`

how to make it show image on my site?

**Comment by xcodebuild** [comment]
Things should work now.

**Comment by 777Arch** [comment]
貌似0.0.2版本修正了该错误，但是在0.0.3版本中，这个问题又出现了
