### ISSUE TITLE
cannot use when add a "/" to the head of the path

### ISSUE THREAD

**Issue by halohoop** [CodeFalling/hexo-asset-image#27]
cannot use when add a "/" to the head of the path
wrong:
`![testMyBlog](/testMyBlog/bottom_sheet.png)`

right:
`![testMyBlog](testMyBlog/bottom_sheet.png)`

hope to enhance it.

**Comment by Goshin** [comment]
A path starts with a "/" is an absolute path, where the leading "/" means the root directory.

So it is quite appropriate in the case you provide.

For the related code, refer to:
https://github.com/CodeFalling/hexo-asset-image/pull/24/files

**Comment by halohoop** [comment]
好的。
可能因为我用的是windows平台吧。
