### ISSUE TITLE
静态文件生成的图片路径不正确

### ISSUE THREAD

**Issue by ghost** [CodeFalling/hexo-asset-image#3]
about路径下有一个文件叫index.md 我在这个路径下创建了一个index文件夹，png图片放在index路径下

about/
-------index,md
-------index

 在index.md文件中插入图片：

！【支付宝扫一扫，请博主喝杯咖啡】(index/ap1g9yh63op41h7z62.png)

生成的src路径是/about/indexhtmlap1g9yh63op41h7z62.png

注：上面为了显示方便，所以符号用的中文符号，我在实际index.md中用的是英文符号。

**Comment by smallx** [comment]
这个问题现在被修复了。

**Comment by xcodebuild** [comment]
@smallx 谢谢😉
