### ISSUE TITLE
图片加载问题

### ISSUE THREAD

**Issue by BG7YWL** [CodeFalling/hexo-asset-image#39]
hexo-asset-image插件已经安装，博客设置如下
![bg7ywl-10-11_11-3-0](https://user-images.githubusercontent.com/9145406/46778252-89045480-cd45-11e8-9277-5cf0546d3059.jpg)
尝试填文件夹图片也不显示
![bg7ywl-10-11_11-3-30](https://user-images.githubusercontent.com/9145406/46778254-89045480-cd45-11e8-92c6-223d6294426b.jpg)
Debug图
![bg7ywl-10-11_11-4-29](https://user-images.githubusercontent.com/9145406/46778255-89045480-cd45-11e8-836c-3cce45519eb3.jpg)

**Comment by frankrx41** [comment]
我在 http://www.itomtan.com/2017/09/29/the-problem-when-use-post-asset-folder/
找到了相關的解決方法
把permalink: 改成permalink: :year/:month/:day/:title/試一下？

**Comment by KivenCkl** [comment]
对于   permalink: post/:abbrlink.html   这种情况，可以修改 hexo-assert-image 插件中 index.js 文件
增加一条语句  link = link.replace('.html', '/');	//新增加，针对修改后的permalink
如图所示
![2018-11-30_204315](https://user-images.githubusercontent.com/23291142/49290089-e6648880-f4e0-11e8-917e-6977cecbc025.png)
