### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by hytaoist** [CodeFalling/hexo-asset-image#4]
我是用hexo + github 搭建的博客。用这个在文章中添加图片。
- 在本地查看博客时：可以正常的显示图片；但是发布到github后，用博客地址就不能查看了。
- 出现的结果就是：The requested content cannot be loaded.Please try again later

**Comment by xcodebuild** [comment]
有链接么？看看`src`具体指向了哪里？

**Comment by hytaoist** [comment]
谢谢，我用了其他方式解决了。[这是我的博客地址](http://hytaoist.github.io)

**Comment by gcgeng** [comment]
请问怎么解决?
