### ISSUE TITLE
   hexo-asset-image 和 hexo-abbrlink 共用导致图片无法正常显示问题

### ISSUE THREAD

**Issue by JunqiFu** [CodeFalling/hexo-asset-image#43]
你好，你的插件非常棒，给我很大的帮助，但是目前我遇到了一个问题，在同时使用   hexo-asset-image 和 hexo-abbrlink 插件时，图片不能正常显示，不知道在 hexo-asset-image 的版本更新过程中能否 实现与 hexo-abbrlink 插件的兼容呢 ？

**Comment by xcodebuild** [comment]
0.0.4 版本应该兼容了

**Comment by JunqiFu** [comment]
最后能够引用图片，我修改了每篇文章和图片存放文件夹的命名，更改成了一段规则的字符串，然后成功了

**Comment by xcodebuild** [comment]
@JunqiFu 感谢反馈
