### ISSUE TITLE
在org-mode下未解析

### ISSUE THREAD

**Issue by xushaobo** [CodeFalling/hexo-asset-image#8]

**Comment by xcodebuild** [comment]
可以描述的更详细些么，我配合 `hexo-renderer-org` 是可以工作的

**Comment by smallx** [comment]
@xushaobo 对哦，请你描述的详细一点哦。

@CodeFalling `hexo-renderer-org`是干啥用的啊？

**Comment by xcodebuild** [comment]
@smallx  用来让 `hexo` 渲染 `org-mode` 的，可以和这个插件一起工作

**Comment by smallx** [comment]
@CodeFalling 好吧，我才听说`org-mode`，貌似很强大。 :smile:

**Comment by xushaobo** [comment]
哇！大神能回答真的很感谢，嗯嗯，我详细描述一下我遇到的问题。首先，按照您的方法，npm install hexo-asset-image --save，
安装了插件，并且确保post_asset_folder: true in your _config.yml ，然后
我在_post目录下新建了一个test目录（目录中有一个example.png文件）和test.org文件，最后我在test.org中输入![example](test/example.png),
在我的git page的index.html中我看到它被解析成：
<p>
![python-repl-sample](Emacs.Tutorial/python-repl-sample.png)
</p> 所以貌似这个插件在我这里并没有起到作用，但我通过修改git page上的这个文件为：<img
src="/2016/06/18/example.png" title="example">却可以正常显示，
但这终究不是长久之计，因为下次提交，这个文件就会改变。

2016-06-18 21:13 GMT+08:00 codefalling notifications@github.com:

**Comment by xushaobo** [comment]
@CodeFalling 也感谢你的hexo-renderer-org这一插件，绝大多数情况下，它都能很好的工作，希望以后这一插件能变得越来越好！

**Comment by xcodebuild** [comment]
@xushaobo 在 `org-mode` 里似乎应该写 

```
#+ATTR_HTML:  :alt 图像标题
file:test/example.png
```

吧，你写的仍然是 `markdown` 语法，可以参考 https://raw.githubusercontent.com/CodeFalling/codefalling.github.io/source/blog/fcitx-vim-for-OS-X.org

**Comment by xushaobo** [comment]
谢谢您的解答，是我的原因，看来以后有问题直接找作者是效率最高的啊，比一个钻牛角尖好多了，再次谢谢您，以后在使用org-render和org-mode的过程中，希望还有机会可以提问😊，比如插件对org文件
中插入latex代码的支持，目前我还没有使它正常工作，准备以后有时间慢慢解决，到时再来提问哈，另外，一定会把这个插件推荐给更多人，配合org-mode真得是很好用，谢谢您的插件

2016-06-18 21:42 GMT+08:00 codefalling notifications@github.com:

**Comment by xcodebuild** [comment]
客气，有问题直接开issue就行
